### ISSUE TITLE
特地过来说声谢谢！

### ISSUE THREAD

**Issue by liweitd** [coronin/thepaperlink-chrome#7]
我是paper link的忠实用户，使用好几年了。昨天paper link不能正常使用，chrome商店也搜不到链接，以为这个插件从此不再维护……
今天突然发现paper link竟然更新了，有种失而复得的感觉。谢谢作者！

**Comment by MaverickChan** [comment]
> 我是paper link的忠实用户，使用好几年了。昨天paper link不能正常使用，chrome商店也搜不到链接，以为这个插件从此不再维护……
> 今天突然发现paper link竟然更新了，有种失而复得的感觉。谢谢作者！

请问那个sci-hub显示在pubmed里的超链接符号小啾啾怎么看不到了？谢谢

**Comment by liweitd** [comment]
点publisher就可以了。

**Comment by liweitd** [comment]
试试publisher吧

**Comment by liweitd** [comment]
同问…

**Comment by liweitd** [comment]
点publisher试试，能连到sci-hub

**Comment by MaverickChan** [comment]
> 点publisher试试，能连到sci-hub

我点了以后直接链接到文章的官方页面。不知道怎么回事？

**Comment by liweitd** [comment]
同一个版本，在家里，publisher是链接到sci-hub；在单位，却是链接到文章的官方页面。
我也不知道是什么原因。

**Comment by liweitd** [comment]
知道是怎么回事了。
publisher本身是链接到官方页面。
我这里之所以能连sci-hub，是因为之前装了脚本“sci-hub automatic link”，纯属误打误撞上的。

**Comment by MaverickChan** [comment]
> 知道是怎么回事了。
> publisher本身是链接到官方页面。
> 我这里之所以能连sci-hub，是因为之前装了脚本“sci-hub automatic link”，纯属误打误撞上的。

我说怎么回事，谢谢你提示得脚本，在油猴脚本里装了这个成功啦，官方那个小啾啾算是去掉了？

**Comment by coronin** [comment]
你登录之后能看到sci-hub的，不登陆看不到：为了通过google webstore。。。
